---
- name: Install required dependencies
  apt:
    name: "{{ powershell_install_dependencies }}"
    state: present
- name: Install Microsoft apt key
  apt_key:
    url: "{{ powershell_microsoft_apt_key }}"
    state: present
- name: Install official Powershell repository
  apt_repository:
    repo: "{{ powershell_repository[ansible_distribution_release] }}"
    state: present
